CREATE TABLE  Person
(
    id   INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Adresse
(
    id      INT PRIMARY KEY,
    wohnort INT NOT NULL,
    FOREIGN KEY (id) REFERENCES Person (id)
);